{
    'name': 'INSW Integration KEK (IT Inventory)',
    'version': '16.0.1.0.0',
    'category': 'Inventory/INSW',
    'summary': 'Integrasi System-to-System INSW untuk Kawasan Ekonomi Khusus',
    'author': 'MH',
    'depends': ['stock', 'product', 'uom','mrp', 'inventory_adjustments_extension', 'inventory_adjustments_beginning'],
    'data': [
        'security/insw_security.xml',
        'security/ir.model.access.csv',
        'data/dashboard_data.xml',
        'views/insw_config_view.xml',
        'views/master_inherit_view.xml',
        'views/insw_queue_view.xml',
        'views/stock_opening_batch_view.xml',
        'views/stock_picking_view.xml',
        'views/mrp_production_view.xml',
        'views/stock_adjustment_batch_view.xml',
        'views/insw_dashboard_view.xml',
        'views/insw_menus.xml',
    ],
    'installable': True,
    'application': True,
}